title: "Jesus Adrian Hernandez Valenzuela"
description: "No solo basta con aprender sino tambi√©n saber como ejecutarl el conocimiento en casos reales!"
logo:

#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
